// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SRD_AltMenuScreen_FF7","status":true,"description":"An alternative menu based off of the menu from Final Fantasy 7.","parameters":{"\"To Next Level\" Text":"To Next Level","\"Play Time\" Text":"Time","Squish \"Play Time\"":"false","Use Display Name":"true","EXP Color 1":"#800080","EXP Color 2":"#FF1AFF","== Menu Status ==":"","Number of Rows":"3","X Offset":"0","Y Offset":"0","Show Class":"true","Show Icons":"true","== Gold/Time ==":"","G/T Window Width":"240","== Location ==":"","L Window Width":"480"}},
<<<<<<< Updated upstream
{"name":"SRD_PressStart","status":false,"description":"Shows a \"Press Start\" styled phrase and waits for input before opening the Command Window on the Title Screen.","parameters":{"Shown Text":"Press Z to Start","Start Condition":"Input.isPressed('ok') || TouchInput.isPressed()","Fading Speed":"4","== Positioning ==":"","Alignment":"center","X Position":"20","Y Position":"Graphics.height * (3/4)","Max Width":"Graphics.width","Max Height":"48","== Text Options ==":"","Font":"GameFont","Font Size":"34","Outline Size":"4","Font Color":"#FFFFFF","Outline Color":"black"}}
=======
{"name":"SRD_PressStart","status":true,"description":"Shows a \"Press Start\" styled phrase and waits for input before opening the Command Window on the Title Screen.","parameters":{"Shown Text":"Press Z to Start","Start Condition":"Input.isPressed('ok') || TouchInput.isPressed()","Fading Speed":"4","== Positioning ==":"","Alignment":"center","X Position":"20","Y Position":"Graphics.height * (3/4)","Max Width":"Graphics.width","Max Height":"48","== Text Options ==":"","Font":"GameFont","Font Size":"34","Outline Size":"4","Font Color":"#FFFFFF","Outline Color":"black"}},
{"name":"Map_revture","status":true,"description":"Floating World Map","parameters":{}}
>>>>>>> Stashed changes
];
